import { TaxCalculation, TransactionData } from '../types/transaction';

interface PDFReportData {
  taxCalculation: TaxCalculation;
  selectedCountry: 'IN' | 'US' | 'UK';
  calculationMethod: 'FIFO' | 'LIFO' | 'HIFO';
  transactions: TransactionData[];
}

const COUNTRY_DATA = {
  IN: { name: 'India', flag: '🇮🇳' },
  US: { name: 'United States', flag: '🇺🇸' },
  UK: { name: 'United Kingdom', flag: '🇬🇧' }
};

export const generatePDFReport = (data: PDFReportData) => {
  const { taxCalculation, selectedCountry, calculationMethod, transactions } = data;
  const country = COUNTRY_DATA[selectedCountry];
  
  // Create HTML content for the PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Crypto Tax Report - ${country.name}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        .header { text-align: center; border-bottom: 3px solid #007BFF; padding-bottom: 20px; margin-bottom: 30px; }
        .country-flag { font-size: 2em; }
        .summary-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 30px 0; }
        .summary-card { background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #007BFF; }
        .amount { font-size: 1.5em; font-weight: bold; color: #007BFF; }
        .negative { color: #dc3545; }
        .positive { color: #28a745; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th, .table td { border: 1px solid #dee2e6; padding: 12px; text-align: left; }
        .table th { background: #007BFF; color: white; }
        .notes { background: #fff3cd; border: 1px solid #ffeaa7; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #dee2e6; color: #6c757d; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="country-flag">${country.flag}</div>
        <h1>Cryptocurrency Tax Report</h1>
        <h2>${country.name}</h2>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
      </div>

      <div class="summary-grid">
        <div class="summary-card">
          <h3>Short-term Capital Gains</h3>
          <div class="amount ${taxCalculation.shortTermGains >= 0 ? 'positive' : 'negative'}">
            $${taxCalculation.shortTermGains.toFixed(2)}
          </div>
          <p>Holdings ≤ 1 year</p>
        </div>
        
        <div class="summary-card">
          <h3>Long-term Capital Gains</h3>
          <div class="amount ${taxCalculation.longTermGains >= 0 ? 'positive' : 'negative'}">
            $${taxCalculation.longTermGains.toFixed(2)}
          </div>
          <p>Holdings > 1 year</p>
        </div>
        
        <div class="summary-card">
          <h3>Total Tax Owed</h3>
          <div class="amount negative">$${taxCalculation.totalTax.toFixed(2)}</div>
          <p>All applicable taxes included</p>
        </div>
        
        <div class="summary-card">
          <h3>Real Earnings</h3>
          <div class="amount ${taxCalculation.realEarnings >= 0 ? 'positive' : 'negative'}">
            $${taxCalculation.realEarnings.toFixed(2)}
          </div>
          <p>After tax & inflation adjustment</p>
        </div>
      </div>

      <h3>Calculation Method</h3>
      <p><strong>${calculationMethod}</strong> - ${getMethodDescription(calculationMethod)}</p>

      <h3>Transaction Summary</h3>
      <table class="table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Asset</th>
            <th>Type</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Value</th>
          </tr>
        </thead>
        <tbody>
          ${transactions.slice(0, 10).map(t => `
            <tr>
              <td>${new Date(t.timestamp).toLocaleDateString()}</td>
              <td>${t.asset}</td>
              <td style="text-transform: capitalize;">${t.type}</td>
              <td>${t.quantity}</td>
              <td>$${t.price.toFixed(2)}</td>
              <td>$${(t.quantity * t.price).toFixed(2)}</td>
            </tr>
          `).join('')}
          ${transactions.length > 10 ? '<tr><td colspan="6" style="text-align: center; font-style: italic;">... and ' + (transactions.length - 10) + ' more transactions</td></tr>' : ''}
        </tbody>
      </table>

      <div class="notes">
        <h3>${country.name} Tax Notes</h3>
        ${getCountryTaxNotes(selectedCountry)}
      </div>

      <div class="footer">
        <p><strong>Disclaimer:</strong> This report is for informational purposes only and does not constitute tax advice. 
        Please consult with a qualified tax professional for personalized advice.</p>
        <p>Generated by CryptoTax Pro | ${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `;

  // Create and download the PDF using browser's print functionality
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load then print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
      }, 250);
    };
  }
};

const getMethodDescription = (method: string): string => {
  switch (method) {
    case 'FIFO': return 'First In, First Out - Oldest coins sold first';
    case 'LIFO': return 'Last In, First Out - Newest coins sold first';
    case 'HIFO': return 'Highest In, First Out - Highest cost coins sold first';
    default: return '';
  }
};

const getCountryTaxNotes = (country: string): string => {
  switch (country) {
    case 'IN':
      return `
        <ul>
          <li>Flat 30% tax rate applies to all crypto gains</li>
          <li>Additional 4% cess on tax amount</li>
          <li>1% TDS on transactions above ₹10,000</li>
          <li>No indexation benefit available</li>
          <li>Losses can only be offset against other crypto gains</li>
        </ul>
      `;
    case 'US':
      return `
        <ul>
          <li>Short-term gains taxed as ordinary income (10% - 37%)</li>
          <li>Long-term gains: 0%, 15%, or 20% based on income</li>
          <li>Report on Form 8949 and Schedule D</li>
          <li>Each crypto transaction may be taxable</li>
          <li>Consider tax-loss harvesting opportunities</li>
        </ul>
      `;
    case 'UK':
      return `
        <ul>
          <li>Capital Gains Tax: 10% or 20% based on total income</li>
          <li>£6,000 annual CGT allowance (2023-24)</li>
          <li>Share pooling method for identical assets</li>
          <li>Report gains above allowance on SA return</li>
          <li>Consider spouse transfers to maximize allowances</li>
        </ul>
      `;
    default:
      return '';
  }
};